2018-12-21 03:01:38,263 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:06:27,111 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:10:45,915 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:11:28,099 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:16:20,558 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:26:33,699 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:26:45,482 ERROR: Exception on /search [GET] [in c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\Shepherd\Program\Flask\microblog\app\main\routes.py", line 124, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "c:\Users\Shepherd\Program\Flask\microblog\app\models.py", line 13, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "c:\Users\Shepherd\Program\Flask\microblog\app\search.py", line 30, in query_index
    'size': per_page
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\client\__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count')
2018-12-21 03:26:47,216 ERROR: Exception on /search [GET] [in c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\Shepherd\Program\Flask\microblog\app\main\routes.py", line 124, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "c:\Users\Shepherd\Program\Flask\microblog\app\models.py", line 13, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "c:\Users\Shepherd\Program\Flask\microblog\app\search.py", line 30, in query_index
    'size': per_page
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\client\__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\users\shepherd\program\flask\microblog\venv\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count')
2018-12-21 03:28:45,146 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
2018-12-21 03:30:32,541 INFO: Microblog startup [in c:\Users\Shepherd\Program\Flask\microblog\app\__init__.py:71]
